#pragma once
typedef unsigned short Color;


// Базовые цвета текста
#define FOREGROUND_WHITE FOREGROUND_BLUE | FOREGROUND_RED | FOREGROUND_GREEN
#define FOREGROUND_BLACK 0
#define FOREGROUND_YELLOW FOREGROUND_RED | FOREGROUND_GREEN
#define FOREGROUND_MAGENTA FOREGROUND_RED | FOREGROUND_BLUE
#define FOREGROUND_CYAN FOREGROUND_GREEN | FOREGROUND_BLUE

// Светлые цвета текста
#define FOREGROUND_BRIGHT_BLACK FOREGROUND_INTENSITY
#define FOREGROUND_BRIGHT_RED FOREGROUND_RED | FOREGROUND_INTENSITY
#define FOREGROUND_BRIGHT_GREEN FOREGROUND_GREEN | FOREGROUND_INTENSITY
#define FOREGROUND_BRIGHT_BLUE FOREGROUND_BLUE | FOREGROUND_INTENSITY
#define FOREGROUND_BRIGHT_YELLOW FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY
#define FOREGROUND_BRIGHT_MAGENTA FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY
#define FOREGROUND_BRIGHT_CYAN FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY
#define FOREGROUND_BRIGHT_WHITE FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY

// Базовые цвета фона
#define BACKGROUND_BLACK 0
#define BACKGROUND_YELLOW BACKGROUND_RED | BACKGROUND_GREEN
#define BACKGROUND_MAGENTA BACKGROUND_RED | BACKGROUND_BLUE
#define BACKGROUND_CYAN BACKGROUND_GREEN | BACKGROUND_BLUE
#define BACKGROUND_WHITE BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE

// Светлые цвета фона
#define BACKGROUND_BRIGHT_BLACK BACKGROUND_INTENSITY
#define BACKGROUND_BRIGHT_RED BACKGROUND_RED | BACKGROUND_INTENSITY
#define BACKGROUND_BRIGHT_GREEN BACKGROUND_GREEN | BACKGROUND_INTENSITY
#define BACKGROUND_BRIGHT_BLUE BACKGROUND_BLUE | BACKGROUND_INTENSITY
#define BACKGROUND_BRIGHT_YELLOW BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY
#define BACKGROUND_BRIGHT_MAGENTA BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY
#define BACKGROUND_BRIGHT_CYAN BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY
#define BACKGROUND_BRIGHT_WHITE BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY

#define DEFAULT_COLOR BACKGROUND_BLACK | FOREGROUND_WHITE